<Project Sdk="Microsoft.NET.Sdk.Razor">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AddRazorSupportForMvc>true</AddRazorSupportForMvc>
    <StaticWebAssetBasePath>App_Plugins/LegacyFeatureConverter</StaticWebAssetBasePath>
	  <ContentTargetFolders>.</ContentTargetFolders>
  </PropertyGroup>

  <PropertyGroup>
    <PackageId>LP.Umbraco.LegacyFeatureConverter</PackageId>
    <Product>LP.Umbraco.LegacyFeatureConverter</Product>
    <Title>LP.Umbraco.LegacyFeatureConverter</Title>
    <Description>...</Description>
    <PackageTags>umbraco plugin package</PackageTags>
  </PropertyGroup>

  <PropertyGroup>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <GeneratePackageOnBuild>True</GeneratePackageOnBuild>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\LP.Umbraco.LegacyFeatureConverter.Abstractions\LP.Umbraco.LegacyFeatureConverter.Abstractions.csproj" />
    <ProjectReference Include="..\LP.Umbraco.LegacyFeatureConverter.Data\LP.Umbraco.LegacyFeatureConverter.Data.csproj" />
    <ProjectReference Include="..\LP.Umbraco.LegacyFeatureConverter.Infrastructure\LP.Umbraco.LegacyFeatureConverter.Infrastructure.csproj" />
    <ProjectReference Include="..\LP.Umbraco.LegacyFeatureConverter.Converters\LP.Umbraco.LegacyFeatureConverter.Converters.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Umbraco.Cms.Web.Website" Version="13.13.1" />
    <PackageReference Include="Umbraco.Cms.Web.BackOffice" Version="13.13.1" />
  </ItemGroup>
</Project>
