<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Umbraco.Community.LegacyFeatureConverter.Abstractions\Umbraco.Community.LegacyFeatureConverter.Abstractions.csproj" />
    <ProjectReference Include="..\Umbraco.Community.LegacyFeatureConverter.Data\Umbraco.Community.LegacyFeatureConverter.Data.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Umbraco.Cms.Infrastructure" Version="13.13.1" />
  </ItemGroup>

</Project>
