<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="LP.Umbraco.LegacyFeatureConverter.Tests" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\LP.Umbraco.LegacyFeatureConverter.Abstractions\LP.Umbraco.LegacyFeatureConverter.Abstractions.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Umbraco.Cms.Infrastructure" Version="13.13.1" />
  </ItemGroup>

</Project>
