// <auto-generated />
using System;
using Umbraco.Community.LegacyFeatureConverter.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Umbraco.Community.LegacyFeatureConverter.Data.Migrations.SqlServer
{
    [DbContext(typeof(LegacyFeatureConverterDbContextSqlServer))]
    [Migration("20260328230739_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Umbraco.Community.LegacyFeatureConverter.Models.ConversionHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("CompletedAt");

                    b.Property<string>("ConverterType")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("ConverterType");

                    b.Property<int>("FailureCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("FailureCount");

                    b.Property<bool>("IsTestRun")
                        .HasColumnType("bit")
                        .HasColumnName("IsTestRun");

                    b.Property<Guid>("PerformingUserKey")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("PerformingUserKey");

                    b.Property<string>("SelectedDocumentTypes")
                        .HasMaxLength(2147483647)
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("SelectedDocumentTypes");

                    b.Property<int>("SkippedCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("SkippedCount");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("StartedAt");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Status");

                    b.Property<int>("SuccessCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("SuccessCount");

                    b.Property<string>("Summary")
                        .HasMaxLength(2147483647)
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Summary");

                    b.Property<int>("TotalContentNodes")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("TotalContentNodes");

                    b.Property<int>("TotalDataTypes")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("TotalDataTypes");

                    b.Property<int>("TotalDocumentTypes")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("TotalDocumentTypes");

                    b.HasKey("Id");

                    b.ToTable("LegacyFeatureConverterHistory", (string)null);
                });

            modelBuilder.Entity("Umbraco.Community.LegacyFeatureConverter.Models.ConversionLogEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id");

                    b.Property<Guid>("ConversionHistoryId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ConversionHistoryId");

                    b.Property<string>("Details")
                        .HasMaxLength(2147483647)
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Details");

                    b.Property<string>("ItemKey")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("ItemKey");

                    b.Property<string>("ItemName")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("ItemName");

                    b.Property<string>("ItemType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("ItemType");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("Level");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("Message");

                    b.Property<string>("StackTrace")
                        .HasMaxLength(2147483647)
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("StackTrace");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2")
                        .HasColumnName("Timestamp");

                    b.HasKey("Id");

                    b.HasIndex("ConversionHistoryId")
                        .HasDatabaseName("IX_LegacyFeatureConverterLog_HistoryId");

                    b.HasIndex("Timestamp")
                        .HasDatabaseName("IX_LegacyFeatureConverterLog_Timestamp");

                    b.ToTable("LegacyFeatureConverterLog", (string)null);
                });

            modelBuilder.Entity("Umbraco.Community.LegacyFeatureConverter.Models.QueueItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("CompletedAt");

                    b.Property<Guid?>("ConversionHistoryId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ConversionHistoryId");

                    b.Property<DateTime>("QueuedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("QueuedAt");

                    b.Property<string>("SerializedOptions")
                        .IsRequired()
                        .HasMaxLength(2147483647)
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("SerializedOptions");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("StartedAt");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Status");

                    b.HasKey("Id");

                    b.HasIndex("QueuedAt")
                        .HasDatabaseName("IX_LegacyFeatureConverterQueue_QueuedAt");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_LegacyFeatureConverterQueue_Status");

                    b.ToTable("LegacyFeatureConverterQueue", (string)null);
                });

            modelBuilder.Entity("Umbraco.Community.LegacyFeatureConverter.Models.ConversionLogEntry", b =>
                {
                    b.HasOne("Umbraco.Community.LegacyFeatureConverter.Models.ConversionHistory", "ConversionHistory")
                        .WithMany("LogEntries")
                        .HasForeignKey("ConversionHistoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ConversionHistory");
                });

            modelBuilder.Entity("Umbraco.Community.LegacyFeatureConverter.Models.ConversionHistory", b =>
                {
                    b.Navigation("LogEntries");
                });
#pragma warning restore 612, 618
        }
    }
}
