<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MSTest" Version="4.0.2" />
    <PackageReference Include="Moq" Version="4.20.72" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="[8.0.22]" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Umbraco.Community.LegacyFeatureConverter.Abstractions\Umbraco.Community.LegacyFeatureConverter.Abstractions.csproj" />
    <ProjectReference Include="..\Umbraco.Community.LegacyFeatureConverter.Data\Umbraco.Community.LegacyFeatureConverter.Data.csproj" />
    <ProjectReference Include="..\Umbraco.Community.LegacyFeatureConverter.Infrastructure\Umbraco.Community.LegacyFeatureConverter.Infrastructure.csproj" />
    <ProjectReference Include="..\Umbraco.Community.LegacyFeatureConverter.Converters\Umbraco.Community.LegacyFeatureConverter.Converters.csproj" />
    <ProjectReference Include="..\Umbraco.Community.LegacyFeatureConverter\Umbraco.Community.LegacyFeatureConverter.csproj" />
  </ItemGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Microsoft.VisualStudio.TestTools.UnitTesting" />
  </ItemGroup>

</Project>
